"use client";
import { useEffect, useState, type FormEvent } from "react";
import "./chicken-arena.css";

type Category = "learning" | "work" | "quality" | "teamwork";
type Chicken = { employeeId:string;name:string;branch:string;department:string;rank:number;totalXp:number;monthlyXp:number;growthXp:number;level:number;progress:number;next:number;isCurrentUser:boolean;stage:{id:string;label:string;sprite:number};categories:Record<Category,number> };
type FarmConfig = { levels:number[];stages:{id:string;label:string;minXp:number;sprite:number}[] };
type Payload = { season:number;branches:string[];leaderboard:Chicken[];config:FarmConfig;canAdjust:boolean;error?:string };
const labels:Record<Category,string>={learning:"การเรียนรู้",work:"ผลงาน",quality:"คุณภาพ",teamwork:"ทีมเวิร์ก"};
function ChickenArt({stage,animate}:{stage:Chicken["stage"];animate:boolean}){const col=stage.sprite%3,row=Math.floor(stage.sprite/3);return <span className={`farm-chicken ${animate?"is-animated":""}`} aria-hidden="true"><img loading="lazy" decoding="async" src="/ole-chicken-stages.png" alt="" style={{left:`${-col*100}%`,top:`${-row*100}%`}}/></span>}

export function ChickenArena(){
 const [section,setSection]=useState<"arena"|"guide">("arena"),[ranking,setRanking]=useState("annual"),[branch,setBranch]=useState(""),[data,setData]=useState<Payload|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[selected,setSelected]=useState<Chicken|null>(null),[saving,setSaving]=useState(false);
 async function load(signal?:AbortSignal){setLoading(true);setError("");try{const query=new URLSearchParams({ranking});if(branch)query.set("branch",branch);const response=await fetch(`/api/farm?${query}`,{cache:"no-store",signal}),payload=await response.json() as Payload;if(!response.ok)throw new Error(payload.error||"โหลดคะแนนไม่สำเร็จ");setData(payload);setSelected(current=>current?payload.leaderboard.find(item=>item.employeeId===current.employeeId)||null:null)}catch(cause){if((cause as Error).name!=="AbortError"){setData(null);setError(cause instanceof Error?cause.message:"โหลดคะแนนไม่สำเร็จ")}}finally{if(!signal?.aborted)setLoading(false)}}
 useEffect(()=>{const controller=new AbortController();queueMicrotask(()=>void load(controller.signal));return()=>controller.abort()},[ranking,branch]);
 async function adjust(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected||saving||!data)return;const element=event.currentTarget;setSaving(true);setError("");const form=new FormData(element);try{const response=await fetch("/api/farm",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({employeeId:selected.employeeId,category:form.get("category"),amount:Number(form.get("amount")),reason:form.get("reason"),season:data.season,idempotencyKey:`admin:${crypto.randomUUID()}`})}),payload=await response.json() as {error?:string};if(!response.ok)throw new Error(payload.error||"ปรับ XP ไม่สำเร็จ");element.reset();await load()}catch(cause){setError(cause instanceof Error?cause.message:"ปรับ XP ไม่สำเร็จ")}finally{setSaving(false)}}
 return <section className="farm-arena">
  <header className="farm-hero"><div><small>OLE FARM · ฤดูกาล {data?.season||new Date().getFullYear()}</small><h2>Chicken Arena</h2><p>ทุกแต้มมาจากงานและการเรียนรู้ที่บันทึกจริง</p></div><span>🏆 ทีม OLE CONNECT</span></header>
  <nav className="farm-section-tabs" aria-label="เมนู OLE FARM"><button className={section==="arena"?"active":""} onClick={()=>setSection("arena")}>สนามไก่และอันดับ</button><button className={section==="guide"?"active":""} onClick={()=>setSection("guide")}>วิธีเล่นและการเติบโต</button></nav>
  {section==="arena"&&<>
  <div className="farm-controls"><div className="farm-tabs" role="tablist" aria-label="รูปแบบการจัดอันดับ">{[["annual","รวมปี"],["monthly","เดือนนี้"],["growth","พัฒนาการ"]].map(([id,label])=><button key={id} role="tab" aria-selected={ranking===id} className={ranking===id?"active":""} onClick={()=>setRanking(id)}>{label}</button>)}</div><label><span>สาขา</span><select value={branch} onChange={event=>setBranch(event.target.value)}><option value="">ทุกสาขา</option>{data?.branches.map(item=><option key={item}>{item}</option>)}</select></label></div>
  {error&&<div className="farm-error" role="alert"><strong>ยังแสดงคะแนนไม่ได้</strong><span>{error}</span><button onClick={()=>void load()}>ลองใหม่</button></div>}
  {loading?<div className="farm-grid" aria-label="กำลังโหลด">{Array.from({length:8},(_,i)=><div className="farm-skeleton" key={i}/>)}</div>:data&&!data.leaderboard.length?<div className="farm-empty"><strong>ยังไม่มีพนักงานในสาขานี้</strong><p>เลือกทุกสาขา หรือเพิ่มพนักงานที่กำลังใช้งานก่อน</p></div>:data?<div className="farm-grid">{data.leaderboard.map(item=><button className={`farm-card ${item.rank<=3?"top":""}`} key={item.employeeId} onClick={()=>setSelected(item)} aria-label={`อันดับ ${item.rank} ${item.name} ${item.totalXp} XP`}><span className="farm-rank">{item.rank<=3?["🥇","🥈","🥉"][item.rank-1]:`#${item.rank}`}</span><ChickenArt stage={item.stage} animate={item.rank<=3||item.isCurrentUser}/><strong>{item.name}</strong><small>{item.branch}</small><b>{item.stage.label}</b><div className="farm-level"><span>Lv.{item.level}</span><span>{ranking==="monthly"?`${item.monthlyXp} XP เดือนนี้`:ranking==="growth"?`${item.growthXp>=0?"+":""}${item.growthXp} XP`:`${item.totalXp} XP`}</span></div><span className="farm-progress"><i style={{width:`${item.progress}%`}}/></span><em>{item.next>item.totalXp?`อีก ${item.next-item.totalXp} XP ถึงเลเวลถัดไป`:"เลเวลสูงสุด"}</em></button>)}</div>:null}
  {selected&&<div className="farm-modal" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setSelected(null)}}><section role="dialog" aria-modal="true" aria-labelledby="farm-detail-title"><button className="farm-close" aria-label="ปิด" onClick={()=>setSelected(null)}>×</button><ChickenArt stage={selected.stage} animate={selected.isCurrentUser}/><div><small>อันดับ #{selected.rank} · {selected.branch}</small><h3 id="farm-detail-title">{selected.name}</h3><p>{selected.stage.label} · Level {selected.level} · {selected.totalXp} XP</p></div><div className="farm-category-grid">{(Object.keys(labels) as Category[]).map(key=><article key={key}><span>{labels[key]}</span><strong>{selected.categories[key]} XP</strong></article>)}</div>{data?.canAdjust&&<form className="farm-adjust" onSubmit={adjust}><h4>ปรับ XP โดยผู้ดูแล</h4><label>หมวด<select name="category" required>{(Object.keys(labels) as Category[]).map(key=><option value={key} key={key}>{labels[key]}</option>)}</select></label><label>จำนวน XP<input name="amount" type="number" min="-1000" max="1000" step="1" required/></label><label className="wide">เหตุผล<input name="reason" maxLength={500} required/></label><button disabled={saving}>{saving?"กำลังบันทึก…":"บันทึกพร้อม Audit Log"}</button></form>}</section></div>}
  </>}
  {section==="guide"&&<FarmGuide data={data} loading={loading}/>}
 </section>
}

function FarmGuide({data,loading}:{data:Payload|null;loading:boolean}){
 if(loading&&!data)return <div className="farm-guide-loading">กำลังโหลดกติกา OLE FARM…</div>;
 if(!data)return <div className="farm-empty"><strong>ยังเปิดกติกาไม่ได้</strong><p>กดกลับไปสนามไก่แล้วลองโหลดใหม่อีกครั้ง</p></div>;
 return <div className="farm-guide">
  <section className="farm-guide-intro"><div><small>คู่มือฤดูกาล {data.season}</small><h3>เลี้ยงไก่ด้วยผลงานจริง</h3><p>ไก่โตจาก XP ที่ระบบคำนวณจากงานซึ่งผู้ตรวจอนุมัติแล้วและผลสอบ SOP เท่านั้น ไม่ใช้ AI ตัดสินคะแนน และรายการเดิมรับแต้มซ้ำไม่ได้</p></div><b>{data.config.levels.length} Levels · {data.config.stages.length} ร่างวิวัฒนาการ</b></section>
  <section className="farm-guide-panel"><header><h3>Level ทั้งหมด</h3><p>แต้มสะสมในฤดูกาลปัจจุบัน</p></header><div className="farm-level-table">{data.config.levels.map((xp,index)=><article key={xp}><b>Lv.{index+1}</b><span>{xp.toLocaleString("th-TH")} XP</span><small>{index===data.config.levels.length-1?"ระดับสูงสุด":`ถึง ${(data.config.levels[index+1]-1).toLocaleString("th-TH")} XP`}</small></article>)}</div></section>
  <section className="farm-guide-panel"><header><h3>การเติบโตของไก่</h3><p>Chicken Stage เปลี่ยนอัตโนมัติเมื่อ Total XP ถึงเกณฑ์</p></header><div className="farm-stage-road">{data.config.stages.map(stage=><article key={stage.id}><ChickenArt stage={stage} animate={false}/><div><strong>{stage.label}</strong><span>เริ่มที่ {stage.minXp.toLocaleString("th-TH")} XP</span></div></article>)}</div></section>
  <section className="farm-guide-panel"><header><h3>ทำอะไรแล้วได้ XP</h3><p>คะแนนเข้าหลังมีผลสำเร็จจริงในระบบ</p></header><div className="farm-rule-grid"><article><b>งาน</b><strong>+20 XP</strong><p>งานที่ผู้ตรวจอนุมัติสำเร็จ งานสำคัญสูง +5 และงานด่วน +10 เพิ่มเติม</p></article><article><b>คุณภาพ</b><strong>+10 / +5 XP</strong><p>ผ่านตั้งแต่การส่งครั้งแรกได้ 10 XP หากเคยส่งกลับแก้ไขได้ 5 XP</p></article><article><b>การเรียนรู้</b><strong>+10–25 XP</strong><p>สอบ SOP ได้ 10 XP + คะแนนตามผลสอบทุก 10% และโบนัส Critical ผ่านครบ +5 XP</p></article><article><b>ทีมเวิร์ก</b><strong>+5 XP</strong><p>ผู้ตรวจได้รับแต้มเมื่ออนุมัติงานของพนักงานคนอื่น</p></article></div></section>
  <section className="farm-guide-notes"><h3>เรื่องที่ควรรู้</h3><ul><li><b>รวมปี</b> เรียงจาก XP ทั้งหมดในฤดูกาล</li><li><b>เดือนนี้</b> เรียงจาก XP ที่ได้ในเดือนปัจจุบัน</li><li><b>พัฒนาการ</b> เปรียบเทียบ XP เดือนนี้กับเดือนก่อน</li><li>คะแนนเท่ากันได้อันดับร่วมกัน และแอดมินปรับ XP ได้เมื่อระบุเหตุผล โดยระบบเก็บ Audit Log ทุกครั้ง</li><li>ข้อมูลส่วนตัวและรายละเอียดการประเมินที่เป็นความลับจะไม่แสดงในสนามไก่</li></ul></section>
 </div>
}
